---
abstract: 'Run SNMP requests with Mojo::IOLoop'
author:
  - 'Jan Henning Thorsen - jhthorsen@cpan.org'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-SNMP
no_index:
  directory:
    - inc
    - t
recommends:
  Crypt::DES: 0
  Digest::HMAC: 0
  Test::Compile: 0
requires:
  Errno: 1.13
  Mojolicious: 3.38
  Net::SNMP: 0
  Scalar::Util: 1.2
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Mojo-SNMP
  homepage: https://metacpan.org/release/Mojo-SNMP
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhthorsen/mojo-snmp.git
version: 0.01
